/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho.Main;

/**
 *
 * @author lucas
 */
public class CadastrarAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAluno
     */
    public CadastrarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menorIdadeGrupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        alunoNome = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        alunoEmail = new javax.swing.JTextField();
        Celular = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alunoEndereco = new javax.swing.JTextArea();
        alunoCpf = new javax.swing.JFormattedTextField();
        alunoCelular = new javax.swing.JFormattedTextField();
        menorIdade = new javax.swing.JRadioButton();
        maiorIdade = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Foco Fitness");

        Nome.setText("Nome do aluno");
        Nome.setName("Nome"); // NOI18N

        alunoNome.setName("alunoNome"); // NOI18N
        alunoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoNomeActionPerformed(evt);
            }
        });

        CPF.setText("CPF do aluno");
        CPF.setName("Nome"); // NOI18N

        Email.setText("Email do aluno");
        Email.setName("Nome"); // NOI18N

        alunoEmail.setName("alunoEmail"); // NOI18N
        alunoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoEmailActionPerformed(evt);
            }
        });

        Celular.setText("Celular do aluno");
        Celular.setName("Nome"); // NOI18N

        Endereco.setText("Endereço do aluno");
        Endereco.setName("Nome"); // NOI18N

        alunoEndereco.setColumns(20);
        alunoEndereco.setRows(5);
        alunoEndereco.setName("alunoEndereco"); // NOI18N
        jScrollPane1.setViewportView(alunoEndereco);

        try {
            alunoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        alunoCpf.setName("alunoCpf"); // NOI18N
        alunoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoCpfActionPerformed(evt);
            }
        });

        try {
            alunoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        alunoCelular.setName("alunoCelular"); // NOI18N

        menorIdadeGrupo.add(menorIdade);
        menorIdade.setText("Sim");
        menorIdade.setName("menorIdade"); // NOI18N

        menorIdadeGrupo.add(maiorIdade);
        maiorIdade.setSelected(true);
        maiorIdade.setText("Não");
        maiorIdade.setName("maiorIdade"); // NOI18N

        jLabel2.setText("É menor de idade?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Nome)
                        .addComponent(alunoNome)
                        .addComponent(CPF)
                        .addComponent(Email)
                        .addComponent(alunoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(Celular)
                        .addComponent(Endereco)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alunoCpf))
                    .addComponent(alunoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menorIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maiorIdade))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Celular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alunoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Endereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menorIdade)
                    .addComponent(maiorIdade))
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alunoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoNomeActionPerformed

    private void alunoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoEmailActionPerformed

    private void alunoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Nome;
    private javax.swing.JFormattedTextField alunoCelular;
    private javax.swing.JFormattedTextField alunoCpf;
    private javax.swing.JTextField alunoEmail;
    private javax.swing.JTextArea alunoEndereco;
    private javax.swing.JTextField alunoNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maiorIdade;
    private javax.swing.JRadioButton menorIdade;
    private javax.swing.ButtonGroup menorIdadeGrupo;
    // End of variables declaration//GEN-END:variables
}
